services:
  backend:
    build: ./server
    container_name: echo_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/echochamber
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: echo_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: echo_redis
    ports:
      - "6379:6379"

  frontend:
    build: ./client
    container_name: echo_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: